version: "1"
name: homework
services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST = mongo:27017
      - SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES = true
      - SERVER_SERVLET_CONTEXT_PATH = "/"

  mongo:
    container_name: "mongo"
    image: "mongo"
    ports:
      - "27017:27017"

networks:
  default:
    name: mongodb_network