spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  options_filename: "options.csv"
  questions_filename: "questions.csv"
  percent_of_correct_answers_required: 80.0
  locale: "ru_RU"
