spring:
  main:
    allow-circular-references: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog

application:
  sql_before_filename: "before.sql"
  sql_after_filename: "after.sql"