management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true